apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web-app
  labels:
    app: devops-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-web-app
  template:
    metadata:
      labels:
        app: devops-web-app
    spec:
      containers:
      - name: devops-web-app
        image: devopsprojectacr2025.azurecr.io/devops-web-app:v1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: devops-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: devops-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
